// generated by stringer -type IkeSaState,IkeEventId -output strings.go; DO NOT EDIT

package state

import "fmt"

const _IkeSaState_name = "SMI_INITSMI_AUTHSMI_AUTH_WAITSMI_AUTH_PEERSMI_EAPSMI_INSTALLCSA_DLSMI_INSTALLCSASMR_INITSMR_AUTHSMR_AUTH_FINALIZESMR_AUTH_RESPONSE_IDSMR_AUTH_RESPONSESMR_EAP_INITATOR_REQUESTSMR_EAP_AAA_REQUESTSMR_AUTH_DL_PEERSMR_CFG_WAITSM_MATURESM_REKEYSM_CRL_UPDATESM_REAUTHSM_TERMINATESM_DYINGSM_DEADSA_INITSA_CREATESA_CREATE_WAITSA_MATURESA_REKEYSA_REKEY_WAITSA_REMOVESA_DEAD"

var _IkeSaState_index = [...]uint16{0, 8, 16, 29, 42, 49, 66, 80, 88, 96, 113, 133, 150, 174, 193, 209, 221, 230, 238, 251, 260, 272, 280, 287, 294, 303, 317, 326, 334, 347, 356, 363}

func (i IkeSaState) String() string {
	i -= 1
	if i < 0 || i+1 >= IkeSaState(len(_IkeSaState_index)) {
		return fmt.Sprintf("IkeSaState(%d)", i+1)
	}
	return _IkeSaState_name[_IkeSaState_index[i]:_IkeSaState_index[i+1]]
}

const _IkeEventId_name = "ACQUIRECONNECTREAUTHN_COOKIEN_INVALID_KEN_NO_PROPOSAL_CHOSENIKE_SA_INIT_RESPONSEIKE_AUTH_RESPONSEDELETE_IKE_SA_RESPONSEIKE_SA_INIT_SUCCESSIKE_AUTH_SUCCESSDELETE_IKE_SA_SUCCESSINVALID_KEIKE_REKEYIKE_REKEY_RESPONSEIKE_DPDIKE_CRL_UPDATEIKE_REAUTHIKE_TERMINATEIKE_LEASE_RENEWIKE_TIMEOUTStateEntryStateExit"

var _IkeEventId_index = [...]uint16{0, 7, 14, 20, 28, 40, 60, 80, 97, 119, 138, 154, 175, 185, 194, 212, 219, 233, 243, 256, 271, 282, 292, 301}

func (i IkeEventId) String() string {
	i -= 1
	if i < 0 || i+1 >= IkeEventId(len(_IkeEventId_index)) {
		return fmt.Sprintf("IkeEventId(%d)", i+1)
	}
	return _IkeEventId_name[_IkeEventId_index[i]:_IkeEventId_index[i+1]]
}
