// Code generated by "stringer -type State,Event -output strings.go"; DO NOT EDIT

package state

import "fmt"

const _State_name = "STATE_IDLESTATE_STARTSTATE_INITSTATE_AUTHSTATE_MATURESTATE_FINISHED"

var _State_index = [...]uint8{0, 10, 21, 31, 41, 53, 67}

func (i State) String() string {
	if i >= State(len(_State_index)-1) {
		return fmt.Sprintf("State(%d)", i)
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}

const _Event_name = "SUCCESSFAILMSG_INITMSG_AUTHMSG_CHILD_SAMSG_DELETE_IKE_SASMI_STARTREKEY_STARTTIMEOUTINIT_FAILAUTH_FAILDELETE_IKE_SAFINISHEDENTRY_EVENT"

var _Event_index = [...]uint8{0, 7, 11, 19, 27, 39, 56, 65, 76, 83, 92, 101, 114, 122, 133}

func (i Event) String() string {
	if i >= Event(len(_Event_index)-1) {
		return fmt.Sprintf("Event(%d)", i)
	}
	return _Event_name[_Event_index[i]:_Event_index[i+1]]
}
