// generated by stringer -type State,Event -output strings.go; DO NOT EDIT

package state

import "fmt"

const _State_name = "STATE_IDLESTATE_INITSTATE_AUTHSTATE_MATURESTATE_FINISHED"

var _State_index = [...]uint8{0, 10, 20, 30, 42, 56}

func (i State) String() string {
	if i+1 >= State(len(_State_index)) {
		return fmt.Sprintf("State(%d)", i)
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}

const _Event_name = "SUCCESSFAILMSG_INITMSG_AUTHMSG_CHILD_SASMI_STARTREKEY_STARTTIMEOUTINIT_FAILAUTH_FAILDELETE_IKE_SAFINISHED"

var _Event_index = [...]uint8{0, 7, 11, 19, 27, 39, 48, 59, 66, 75, 84, 97, 105}

func (i Event) String() string {
	if i+1 >= Event(len(_Event_index)) {
		return fmt.Sprintf("Event(%d)", i)
	}
	return _Event_name[_Event_index[i]:_Event_index[i+1]]
}
